export const scenes = [
  {
    id: "cover",
    type: "cover",
    eyebrow: "非遗青年志",
    title: "狮被之下",
    subtitle: "一个大学生的青春与传承",
    body: "有些热爱，并不是一开始就计划好的。它可能始于一次随意的驻足，始于一阵铿锵的锣鼓声，也始于大一百团大战那天的一个摊位前。",
    visual: "cover",
  },
  {
    id: "reporter-intro",
    type: "reporter",
    eyebrow: "记者手记",
    title: "从锣鼓声里走近醒狮",
    body: "舞狮源于古人对祥瑞与力量的想象，也在岁时节庆、开业庆典和民间仪式中代代流转。新狮启用时，常要经历请狮、净狮、点睛、采青等流程：先敬其形，再唤其神，让沉睡的狮头真正“醒”过来。今天，让我们走进朱朱，了解她与舞狮的故事。",
    visual: "cover",
  },
  {
    id: "letter-photos",
    type: "envelope",
    eyebrow: "采访来信",
    title: "打开这封信",
    body: "轻点信封，让它们一张张跃出纸面。",
    photos: ["./info/email1.jpg", "./info/email2.jpg", "./info/email3.jpg"],
  },
  {
    id: "qa-beginning",
    type: "qa",
    eyebrow: "第一章 被鼓声叫住",
    title: "故事从哪里开始",
    question: "从“偶然接触”到“坚持至今”——你和舞狮的故事是怎么开始的？",
  },
  {
    id: "eye-game",
    type: "game",
    game: "eye",
    eyebrow: "互动 01",
    title: "醒狮点睛",
    body: "按顺序点亮左眼、右眼、天庭与狮口，亲手唤醒狮头的神韵。",
  },
  {
    id: "beginning",
    type: "story",
    eyebrow: "第一章 被鼓声叫住",
    title: "从一次“随便逛逛”开始",
    body: "我和舞狮的缘分开始于大一刚入学百团大战那天。我原本就已经面试了两个学生组织，去百团大战也只是抱着随便逛逛、凑个热闹的心态。",
    visual: "campus",
  },
  {
    id: "booth",
    type: "story",
    eyebrow: "驻足",
    title: "被锣鼓声吸引",
    body: "可就是这份随性闲逛的心情，让我停在了龙狮团的摊位前。精致好看的周边、铿锵振奋的锣鼓声一下子吸引了我，目不转睛地看完了一场精彩绝伦的醒狮表演，我当即就加入了招新群，参加了第一次试训。",
    visual: "sound",
  },
  {
    id: "under-cloth",
    type: "story",
    eyebrow: "走近",
    title: "第一次走进狮被之下",
    body: "在这之前我从未想过自己也能成为狮被下舞动狮子的“雄狮少年”，但从初次体验到正式训练，一场场坚持下来，龙狮团渐渐成了我大学生活里最浓墨重彩的部分，每周的例训也成了我最期待的放松时光。",
    visual: "cloth",
  },
  {
    id: "drum-first",
    type: "story",
    eyebrow: "向往",
    title: "一开始，她只是想学打鼓",
    body: "一开始我其实只想学打鼓，可看着师兄师姐们舞狮时意气风发的模样，心里也生出了向往，也想自己舞出灵动有神韵的狮子，就这样一步步坚持了下来。",
    visual: "training",
  },
  {
    id: "drum-game",
    type: "game",
    game: "drum",
    eyebrow: "互动 02",
    title: "击鼓唤醒舞狮",
    body: "连续敲响鼓面，让沉睡的狮头一点点醒来。",
  },
  {
    id: "heritage",
    type: "story",
    eyebrow: "传承",
    title: "在训练里读懂传承",
    body: "也是在周复一周的训练和相处里，我慢慢读懂了龙狮背后的传统文化，心底多了一份传承的使命感。所以大二我选择留任，成为龙狮团的负责人之一，用心参与招新宣传、参与校内各类大小演出，只希望能让更多同龄人了解龙狮、走近龙狮，真切感受到传统龙狮文化独有的魅力。",
    visual: "poster",
  },
  {
    id: "close-to-heritage",
    type: "story",
    eyebrow: "真正走近",
    title: "非遗，不止是观看",
    body: "其实很多非遗文化都是这样，只有你真正走近去体验去感受，而非只停留在观赏或者走马观花，你才能触摸到文化深层的内涵与魅力，才能做好新一代“文化的传承人”。",
    visual: "pattern",
  },
  {
    id: "collective",
    type: "story",
    eyebrow: "第三章 一群人的热爱",
    title: "她最大的改变，是走进集体",
    body: "舞狮带给我最大的改变，是让我真正学会融入集体、享受集体生活。要是没有加入龙狮团，我的大学生活一定不会这般鲜活多彩。",
    visual: "team",
  },
  {
    id: "partners",
    type: "story",
    eyebrow: "伙伴",
    title: "从一个人，到一群人",
    body: "以前的我性格偏安静，更喜欢一个人独处充电，不太习惯靠集体活动获取归属感。但进入龙狮团之后，我遇到了一群志同道合、真诚温暖的伙伴，大家志趣相投、相处融洽，能玩到一起也能并肩坚持。",
    visual: "silhouette",
  },
  {
    id: "after-training",
    type: "story",
    eyebrow: "训练之后",
    title: "她还想多留一会儿",
    body: "慢慢的，我开始格外珍惜和大家在一起的时光，甚至每次训练结束后，都会期待能多一点相聚相处的机会，和队友相伴的日子，总能让我发自内心地感到放松和快乐。",
    visual: "night",
  },
  {
    id: "ending",
    type: "ending",
    eyebrow: "第四章 青春里的颜料",
    title: "舞狮，是青春里的一盒颜料",
    body: "舞狮于我而言，早已不只是一项爱好，更是我青春里举足轻重的一部分。我始终觉得，一个人能找到自己真正热爱、发自内心喜欢的事，是特别幸运的一件事。如果把我的大学生活比作一张空白的画纸，那舞狮就像是一盒绚烂的颜料。加入龙狮团，让我拥有了这盒颜料；而在训练、团建、表演的点点滴滴里，我慢慢勾勒描绘，添上了一抹又一抹色彩。这些珍贵的经历拼凑在一起，绘成了独属于我的青春画卷。",
    visual: "paper",
  },
];
